import 'styled-system';
import {
  AlignItemsProps,
  BorderProps,
  BorderRadiusProps,
  BordersProps,
  BoxShadowProps,
  ColorProps,
  DisplayProps,
  FlexDirectionProps,
  FlexProps,
  FlexWrapProps,
  FontFamilyProps,
  FontSizeProps,
  FontWeightProps,
  HeightProps,
  JustifyContentProps,
  MaxHeightProps,
  MaxWidthProps,
  MinWidthProps,
  PositionProps,
  SizeProps,
  SpaceProps,
  TextAlignProps,
  WidthProps,
  GridColumnGapProps,
  GridRowGapProps,
  GridColumnProps,
  GridRowProps,
  GridAutoFlowProps,
  GridAutoColumnsProps,
  GridAutoRowsProps,
  GridTemplateColumnsProps,
  GridTemplateRowsProps,
  GridTemplateAreasProps,
  GridAreaProps,
} from 'styled-system';

declare module 'styled-system' {
  export interface SSGridProps extends GridGapProps,
    GridColumnGapProps,
    GridRowGapProps,
    GridColumnProps,
    GridRowProps,
    GridAutoFlowProps,
    GridAutoColumnsProps,
    GridAutoRowsProps,
    GridTemplateColumnsProps,
    GridTemplateRowsProps,
    GridTemplateAreasProps,
    GridAreaProps,
    {}

  export interface StyledSystemProps extends AlignItemsProps,
    BorderProps,
    BordersProps,
    BorderRadiusProps,
    BoxShadowProps,
    ColorProps,
    DisplayProps,
    FlexDirectionProps,
    FlexProps,
    FontFamilyProps,
    FontSizeProps,
    FontWeightProps,
    FlexWrapProps,
    HeightProps,
    JustifyContentProps,
    MaxHeightProps,
    MaxWidthProps,
    MinWidthProps,
    PositionProps,
    SizeProps,
    SpaceProps,
    TextAlignProps,
    WidthProps
    {}

}
