query getArtists {
  artists {
    edges {
      node {
        id
        alias
        avatar {
          url
        }
        name
        albums {
          id
          name
        }
      }
    }
  }
}
