query getArtist($id: ID!) {
  artist(id: $id) {
    id
    alias
    avatar {
      url
    }
    name
    albums {
      id
      artwork {
        id
        url
      }
      artists {
        id
        name
      }
      genres
      name
      releaseDate
      releaseType
      tracks(orderBy: trackNumber_ASC) {
        artists {
          id
          name
        }
        featuring {
          id
          name
        }
        name
        duration
        trackNumber
      }
    }
  }
}
